# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: configure
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
      - name: deploy
        run: |
          cd serverless-lambda/backend
          zip lambda.zip ./*
          aws lambda create-function --function-name test-function --zip-file fileb://lambda.zip --handler index.handler --runtime nodejs10.x --role arn:aws:iam::089801780599:role/harness-delegate-role
